---
- hosts: localhost
  connection: local
  become: true

  tasks:
    #
    # packages
    #
    - name: install packages
      package:
        name:
          - htop
          - tmux
          # dconf depends on psutil
          #- python-psutil
    #
    # wallpapers
    #
    - name: copy wallpaper files
      copy:
        src: files/assets/wallpapers/
        dest: /usr/share/backgrounds/tztz-custom/
        owner: root
        group: root
    - name: set wallpaper
      gsetting:
        org.gnome.desktop.background.picture-uri: "'file:///usr/share/backgrounds/tztz-custom/norway1.jpg'"
    - name: set wallpaper position
      gsetting:
        org.gnome.desktop.background.picture-options: "'zoom'"
